spring:
  application:
    name: $ARTIFACT$-application-boot
  datasource:
    url: jdbc:mysql://localhost:3306/$ARTIFACT$?serverTimezone=GMT%2b8
    username: root
    password: 123456
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl