server:
  port: 18080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/concept?serverTimezone=GMT%2b8
    username: root
    password: 123456
management:
  health:
    rabbit:
      enabled: false
download:
  password: qwe123
#spring:
#  mvc:
#    pathmatch:
#      matching-strategy: path_pattern_parser
#logging:
#  level:
#    org : debug
#debug: true
#concept:
#  download:
#    source:
#      cache:
#        enabled: true #网络资源缓存是否启用
#        path: /Applications/source_cache #网络资源缓存路径，默认为 user.home/concept/download
#        delete: false #下载结束后网络资源缓存是否删除
#    compress:
#      format: zip #压缩格式
#      cache:
#        enabled: false #压缩缓存是否启用
#        path: /compress_cache #压缩缓存路径，默认为 user.home/concept/download
#        delete: false #下载结束后压缩缓存是否删除
#    response:
#      headers: #额外的响应头
#        header1 : 1
#        header2 : 2
#    logger:
#      enabled: true #日志总开关
#      standard:
#        enabled: true #标准流程日志是否启用
#      progress:
#        enabled: true #进度计算日志是否启用，包括加载进度，压缩进度，写入响应进度
#        duration: 500 #进度计算日志输出间隔，ms
#        percentage: true #进度计算日志是否使用百分比输出
#      time-spent:
#        enabled: true #时间计算日志是否启用
#concept:
#  download:
#    compress:
#      cache:
#        enabled: true
#        path: /
#        delete: false
#      format:
#    response:
#      content-type:
#      headers:
#    source:
#      cache:
#        enabled: true
#        delete: true
#        path: /s
#concept:
#  plugin:
#    jar:
#      autoload:
#        location: /home/concept-plugin-jar
#concept:
#  event:
#    kafka:
#      enabled: false
#      endpoints:
#        parent:
#          enabled: false
#          producer:
#            retries: 0
#            acks: 1
#          consumer:
#            enable-auto-commit: false
#          template:
#            default-topic: sample
#          listener:
#            ack-mode: manual_immediate
#        dev:
#          inherit: parent
#          bootstrap-servers:
#            - 192.168.30.140:9092
#          consumer:
#            group-id: sample-dev
#    rabbitmq:
#      enabled: false
#      endpoints:
#        parent:
#          enabled: false
#          username: landsky
#          password: landsky
#          port: 11831
#        dev:
#          inherit: parent
#          host: 192.168.30.140
#          template:
#            routing-key: concept-event.dev
#            exchange: concept-event
concept:
  cloud:
    web:
      intercept:
        request:
          predicate:
            request-path:
              - patterns:
                  - /login
                negate: true
                order: 0
        predicate:
          request-path:
            - patterns:
                - /**/api-docs/**
              negate: true
              order: 0