server:
  port: 18080
#spring:
#  mvc:
#    pathmatch:
#      matching-strategy: path_pattern_parser
#debug: true
#concept:
#  download:
#    compress:
#      cache:
#        enabled: true
#        path: /
#        delete: false
#      format:
#    response:
#      content-type:
#      headers:
#    source:
#      cache:
#        enabled: true
#        delete: true
#        path: /s