server:
  port: 18080
#debug: true
#concept:
#  download:
#    compress:
#      cache:
#        enabled: true
#        path: /
#        delete: false
#      format:
#    response:
#      content-type:
#      headers:
#    source:
#      cache:
#        enabled: true
#        delete: true
concept:
  download:
    log:
      enabled: true
#        path: /s